### ISSUE TITLE
TestNG dependency upgrade to v7.9.0

### ISSUE THREAD

**Issue by itkhanz** [Xray-App/xray-testng-extensions#10]
Hi,
we would like to use this plugin for integrating our TestNG results to Xray. I have noticed that this library uses TestNG version 7.6.0 which is about 2 years old and has a vulnerability.
I would like to know whether an upgrade to latest TestNG release v7.9.0 is possible? so we know that this library also works with the latest TestNG release.

**Comment by itkhanz** [comment]
Thank you for bumping the TestNG dependency version. Is the new release containing this PR coming anytime soon?

**Comment by bitcoder** [comment]
It was already released

**Comment by bitcoder** [comment]
Sorry, I was confusing this with another similar project. I'll have a look at this on the next days

**Comment by itkhanz** [comment]
> Sorry, I was confusing this with another similar project. I'll have a look at this on the next days

Thank you, I look forward to newer release and incorporating this plugin in our projects.
btw it would be better to test the new release of extension with v7.10.x as TestNG did this another big release.

**Comment by bitcoder** [comment]
The release is pending the fix of #12 which is making the tests flaky; I don't have a solution for it (help is appreciated).
Anyway this issue is closed; for discussion, feel free to use the Discussions on the project.
