### ISSUE TITLE
Version 0.3.0 is missing in Maven central repository

### ISSUE THREAD

**Issue by antoncxx** [Xray-App/xray-testng-extensions#25]
Hello,

It seems that the `0.3.0` version is missing from the [Maven Central repository](https://mvnrepository.com/artifact/app.getxray/xray-testng-extensions).

The latest available version in the repository is `0.2.1`.

Are there any plans to update the repository with the `0.3.0` version?

**Comment by bitcoder** [comment]
thanks for reporting @antoncxx; the reason is that the deployment workflow actually failed and I did not double-checked back then.

**Comment by bitcoder** [comment]
related to: https://www.reddit.com/r/java/comments/1dkgh85/psa_maven_central_publishing_requires_token_now/

**Comment by bitcoder** [comment]
fixed
