### ISSUE TITLE
I ran the tests but the TestNG XML report isn't being generated.

### ISSUE THREAD

**Issue by samiir95** [Xray-App/xray-testng-extensions#3]
I've tried to run the "AnnotationExamples" class by enabling the XrayListener by removing the comment line of it from the "org.testng.ITestNGListener" under the test/resources directory but the "testng-results.xml" is not generated!

**Comment by samiir95** [comment]
And after using the default reports for intellij, the report doesn't contain anything related to the used annotations for xray...

**Comment by bitcoder** [comment]
The "AnnotationExamples" is an auxiliary class that is used by the tests within this project, namely by the tests within ReportTests.java.
I'm not sure exactly how you tried to run the tests nor exactly what is the bug you're trying to report? 
You can see [here](https://github.com/Xray-App/tutorial-java-testng-selenium) an example of a project using this project as a client/consumer of this library.

**Comment by samiir95** [comment]
> The "AnnotationExamples" is an auxiliary class that is used by the tests within this project, namely by the tests within ReportTests.java. I'm not sure exactly how you tried to run the tests nor exactly what is the bug you're trying to report? You can see [here](https://github.com/Xray-App/tutorial-java-testng-selenium) an example of a project using this project as a client/consumer of this library.

Yes it was my fault, then I'll close it..
